#!/usr/bin/env bash
# Using awk, sort, and uniq to group visitors by IP and HTTP status code, and display the data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $2, $3, $1}'
