#!/usr/bin/env bash
# Using a while loop and if statement to display "Best School" 10 times
count=1
while [ $count -le 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
