#!/usr/bin/env bash
# Modify nginx.conf to run nginx as nginx user
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Modify default server block to listen on port 8080 and all active IPs
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
